version: '3'
services:
    nginx:
        container_name: nginx
        build:
              context: .
              dockerfile: nginx/Dockerfile
        image: docker-server/nginx
        restart: always
        ports:
          - "80:80"
        volumes:
          - ./serverDev:/srv/docker-server
          - ./log:/var/log/nginx
        depends_on:
          - django

    django:
        container_name: django
        build:
              context : .
              dockerfile: serverDev/Dockerfile
        image: docker-server/django
        restart: always
        command: uwsgi --ini uwsgi.ini
        volumes:
          - ./serverDev:/srv/docker-server
          - ./log:/var/log/uwsgi

    db:
      image: mysql:latest
      container_name: mysql
      ports:
        - "3306:3306"
      environment:
        MYSQL_ROOT_PASSWORD: pro
        MYSQL_DATABASE: product
        MYSQL_USER: pro
        MYSQL_PASSWORD: helloworld
        TZ: 'Asia/Tokyo'
      volumes:
        - ./mysql:/var/lib/mysql
        - ./sql:/docker-entrypoint-initdb.d